spring:
  datasource:
    url: jdbc:mysql://localhost:3306/freezer
    username: root
    password: rootroot
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
